ARRAY

It's the way how you can show a list en numpy.


In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

The way that you can see what type of object you have, is whit the statement "Type" Expample:

In [5]:
type(arr)

numpy.ndarray

We can create an array type matrix, with more dimenssion, as we see the array has a 1 dimenssion, but with a matrix we can have 2, 3, 4 or any dimenssion that you need.

In [18]:
matriz = [[1,2,3], [4,5,6], [7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

We can access to different position in the array, for explample if we need to access to position 4, have to type arra = [# of position that I need], have to remember that the position in the array initiate in the position cero (0). Ex:

In [8]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr[4]

5

we can also to add (position) between them. we want to add the position 2 and 3 (3 + 4)

In [11]:
arr[2] + arr [3]

7

In [19]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now, how can we access an one position in a matrix?, When we have a matrix, need to indicate first "the row" and second "the columm", in this case the row 0 = [1,2,3], row 1 = [4,5,6] and row 2 = [7.,8,9].

If we wanna access to the number 6, we have to type row = 1 and columm =2 Ex:

In [20]:
matriz[1,2]

6

We also can access more than one position with the statement (:), without the limit

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[1:4]

array([2, 3, 4])

We also can access from the end to the start with the symbol (-) to whatever position. Either from an array than matrix. Ex:

In [25]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr[-4]

6

In [27]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
matriz[0:2,0:2]

array([[1, 2],
       [4, 5]])