In [1]:
import numpy as np

We can create all type of array, such as random.rand, arange, ones, zeros, linspace or eye. every one of these arrays have a particular feature.

As in Python, to create a list we use the expression range(0,10), in Numpy we use the statement "arrange(0,10). Ex:

In [8]:
A = np.arange(0,10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.eye(10,10)
## This expression works to create a vector

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [18]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [23]:
np.random.rand(2,20)
# This Expression create random number  decimals from zero to 20 

array([[0.769671  , 0.74648296, 0.00458545, 0.27274865, 0.17734846,
        0.95441657, 0.95271034, 0.6577739 , 0.24810606, 0.22565047,
        0.87565837, 0.56930727, 0.59404388, 0.45375868, 0.25870122,
        0.87284749, 0.08334491, 0.70358619, 0.6238823 , 0.34691213],
       [0.64710166, 0.06802198, 0.01836613, 0.00862029, 0.9633264 ,
        0.60250103, 0.02012314, 0.87136249, 0.45351011, 0.5547955 ,
        0.52483665, 0.24231353, 0.0384154 , 0.05136995, 0.52082953,
        0.2422173 , 0.85022937, 0.04909716, 0.30328007, 0.36810588]])

In [25]:
np.random.rand(4)

array([0.02109515, 0.40064753, 0.01524011, 0.64404461])

In [26]:
np.random.randint(1,20)
##This expression create random number integer from 1 to 20

18

If we wanna create a matrix with random number, we only need to write:


In [27]:
np.random.randint(1,20, (5,5))

array([[16, 19,  5, 15, 10],
       [ 2, 19, 17, 15,  6],
       [ 4,  6, 11,  3,  8],
       [17, 17,  7,  1,  4],
       [12,  4, 13,  1,  9]])