In [1]:
import numpy as np

With the command Shape we can know how many elements we have in each dimension.

For Expample: we can hve an array with 2 dimension  arr = ([1,2,3], [4,5,6]), in this array we can see that we have 2 dimension of (2,3) two rows and 3 columns.

In [11]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)

2
(2, 3)


In [13]:
arr2 = np.random.randint(2,20, (4,8))
print(arr2)
print(arr2.shape)

[[19 11 17  8  4  2  3  3]
 [ 8 12 17 12 11  7 12  2]
 [10 17 16 13  3  9 14  8]
 [15 12  7 13  2  5 10  9]]
(4, 8)


Now, Reshape is a command that helps us to change the form of our array, If we have an tensor of (4,8), we have 32 elements in the array. as the before example we have and tensor of 4 rows ans 8 colummns, but if we wanna change this form and now we wanna have an array of 16 rows ans 2 columns (16,2) or 2 rows and 16 columns (2,16), with the command "reshape" we can do it. Obviously we have to keep the numbers of elements in the array

In [23]:
print(arr2.reshape(2,16))
print(arr2.reshape(16,2))

[[19 11 17  8  4  2  3  3  8 12 17 12 11  7 12  2]
 [10 17 16 13  3  9 14  8 15 12  7 13  2  5 10  9]]
[[19 11]
 [17  8]
 [ 4  2]
 [ 3  3]
 [ 8 12]
 [17 12]
 [11  7]
 [12  2]
 [10 17]
 [16 13]
 [ 3  9]
 [14  8]
 [15 12]
 [ 7 13]
 [ 2  5]
 [10  9]]


In [34]:
##This is other way to write this command

print(np.reshape(arr2, (2,16)))
print(np.size(arr2))

[[19 11 17  8  4  2  3  3  8 12 17 12 11  7 12  2]
 [10 17 16 13  3  9 14  8 15 12  7 13  2  5 10  9]]
32


We also can indicate how we wanna read the array, either columns ("F"), or rows ("C")

In [28]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr3    

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
np.reshape(arr3,(3,4),"C")


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
print(np.reshape(arr3,(3,4), "F"))
print(np.size(arr3))

[[ 1 10  8  6]
 [ 4  2 11  9]
 [ 7  5  3 12]]
12
