In [1]:
import numpy as np

In [5]:
matriz = np.random.randint(1,200,10)
print(matriz.size)
matriz

10


array([178,  28,  97,  10,   3, 100,  84,  19, 192, 104])

In [9]:
m =matriz.reshape(5,2)
m

array([[178,  28],
       [ 97,  10],
       [  3, 100],
       [ 84,  19],
       [192, 104]])

We have different functions or command in Numpy like:

## Max
number maximum of thew array, we also can know the max by rows or columns, only need to indicate 0 = columns or 1 = rows





In [20]:
m

array([[178,  28],
       [ 97,  10],
       [  3, 100],
       [ 84,  19],
       [192, 104]])

In [28]:
print(m.max())
print(m.max(1))
print(m.max(0))

192
[178  97 100  84 192]
[192 104]


## Argmax

Argmax indicate the position of biggest number in the array

In [29]:
m

array([[178,  28],
       [ 97,  10],
       [  3, 100],
       [ 84,  19],
       [192, 104]])

In [31]:
print(m.argmax())
print(m.argmax(0))
print(m.argmax(1))

8
[4 4]
[0 0 1 0 0]


## Min

The same way that "max" min indicates us the minimum number of the array 

In [32]:
m

array([[178,  28],
       [ 97,  10],
       [  3, 100],
       [ 84,  19],
       [192, 104]])

In [35]:
print(m.min())
print(m.min(0))
print(m.min(1))

print(m.argmin())
print(m.argmin(0))
print(m.argmin(1))

3
[ 3 10]
[ 28  10   3  19 104]
4
[2 1]
[1 1 0 1 1]


## Percentiles 

are used in statistics to give you a number that describes the value that a given percent of the values are lower than.

Ex: we have the ages of some student and we wanna know the 50 percentile. 

So the answer is 31, the 50% of the student are 31  years old or younger

In [48]:
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

np.percentile(ages, 50)

31.0

In [49]:
## Sort helps us to sort pur array
ages


[5, 31, 43, 48, 50, 41, 7, 11, 15, 39, 80, 82, 32, 2, 8, 6, 25, 36, 27, 61, 31]

In [50]:
np.sort(ages)

array([ 2,  5,  6,  7,  8, 11, 15, 25, 27, 31, 31, 32, 36, 39, 41, 43, 48,
       50, 61, 80, 82])

## Standar desviation

In [51]:
m

array([[178,  28],
       [ 97,  10],
       [  3, 100],
       [ 84,  19],
       [192, 104]])

In [52]:
np.std(m)

63.765586329931914

## Concatenate

With concatenate we can merge different arrays.

Note: The arrays have to have the same dimmensions

In [77]:
new = np.random.randint(5,20,10)
new

array([ 5,  9, 19, 15, 15, 18,  6,  7,  8,  8])

In [102]:
new2 = np.reshape(new, (5,2))
new2

array([[ 5,  9],
       [19, 15],
       [15, 18],
       [ 6,  7],
       [ 8,  8]])

In [81]:
other = np.random.randint(1,23,6)
other

array([20, 12,  8, 13, 19,  1])

In [106]:
other2 = np.reshape(other,(3,2))
other2

array([[20, 12],
       [ 8, 13],
       [19,  1]])

In [125]:
np.concatenate(new2, other2, axis = 1)

TypeError: concatenate() got multiple values for argument 'axis'

1
1


If we wanna concatenate these arrays we need to add more dimentions at the secound arrays "Other"

In [134]:
new = np.random.randint(5,20,10)
new2 = np.reshape(new, (5,2))
other = np.random.randint(1,23,6)
other2 = np.reshape(other,(3,2))
result = np.concatenate((new2, other2), axis=0)
result

array([[10, 12],
       [11, 19],
       [18, 12],
       [16,  5],
       [18,  7],
       [17,  6],
       [ 8,  9],
       [ 2,  7]])