In [2]:
import numpy as np

## Copy

Copy helps us to work without damage the origin array. If we wanna work with an array, but I don't wanna create a new arange, we can use de command "Copy", with this statement we can work with different formats, always having the origin array.

In [5]:
arr = np.arange (10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 = arr.copy()


In [9]:
arr2[:4] = 100
arr2

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr2

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])