In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10, 10, dtype= "int")
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
frist_cond = arr > 4
frist_cond


array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [5]:
arr[frist_cond]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[(frist_cond) & (arr <7)]

array([5, 6])

In [11]:
n= np.arange(2,50)
n

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
matriz = np.reshape(n, (6,8))
matriz

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

In [14]:
nm = matriz >= 30
matriz[nm]


array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [18]:
matriz[(nm) & (matriz <= 42)]


array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])