In [1]:
import numpy as np

## Operations

We have different operations such as add - substract - divide - multiply what ever type of operationthat we want to.

In [2]:
arr = np.arange(1, 51)
arr2 = arr.copy().reshape(10,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [4]:
new = np.random.randint(2,200, (10,5))
new

array([[ 76,  55,  96, 110, 121],
       [120, 169, 184, 152,  63],
       [139,  39,  81,  26, 197],
       [ 94, 184, 192,  37,  40],
       [ 76,  32,  13,  23, 186],
       [  2,  55, 133,  38,  35],
       [ 86,  10, 163,  86,  48],
       [184, 151, 124,  23,  39],
       [ 49, 158,  60, 161, 165],
       [ 93,  36,  20,  37, 117]])

In [6]:
new - arr2

array([[ 75,  53,  93, 106, 116],
       [114, 162, 176, 143,  53],
       [128,  27,  68,  12, 182],
       [ 78, 167, 174,  18,  20],
       [ 55,  10, -10,  -1, 161],
       [-24,  28, 105,   9,   5],
       [ 55, -22, 130,  52,  13],
       [148, 114,  86, -16,  -1],
       [  8, 116,  17, 117, 120],
       [ 47, -11, -28, -12,  67]])

In [7]:
diagonal = np.diagonal(arr2 * new)
diagonal

array([  76, 1183, 1053,  703, 4650])

In [8]:
arr2 * new

array([[  76,  110,  288,  440,  605],
       [ 720, 1183, 1472, 1368,  630],
       [1529,  468, 1053,  364, 2955],
       [1504, 3128, 3456,  703,  800],
       [1596,  704,  299,  552, 4650],
       [  52, 1485, 3724, 1102, 1050],
       [2666,  320, 5379, 2924, 1680],
       [6624, 5587, 4712,  897, 1560],
       [2009, 6636, 2580, 7084, 7425],
       [4278, 1692,  960, 1813, 5850]])

In [10]:
arr2 / new
media = np.median(arr2 / new)
media

0.291383701188455